openapi: 3.0.1
info:
  title: Fetch
  description: A plugin to fetch web content in Markdown format for ChatGPT.
  version: 'v1'
servers:
  - url: https://fetch.qfd.repl.co
paths:
  /fetchContent:
    get:
      operationId: fetchContent
      summary: Fetch the content of a website in Markdown format.
      parameters:
        - in: query
          name: url
          schema:
            type: string
          required: true
          description: The target URL to fetch content from
        - in: query
          name: chunk
          schema:
            type: integer
            default: 1
          required: false
          description: The chunk number of the response (content is chunked if too long)
      responses:
        '200':
          description: The content of the website in Markdown format
          content:
            text/plain:
              schema:
                type: string
        '429':
          description: Too many requests. Please try again later.
        '500':
          description: Error fetching website content
